I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 35, in script call
    call chapter2start
  File "game/scripts/script.rpy", line 35, in script call
    call chapter2start
ScriptError: could not find label 'chapter2start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 35, in script call
    call chapter2start
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/scripts/script.rpy", line 35, in script call
    call chapter2start
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'chapter2start'.

macOS-14.0-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
dreamscapes 1.0
Wed Feb 21 17:16:15 2024
