I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 13, in script call
    call chapter1start
  File "game/scripts/chapter1.rpy", line 17, in script call
    call nah
  File "game/scripts/script.rpy", line 13, in script call
    call chapter1start
  File "game/scripts/chapter1.rpy", line 17, in script call
    call nah
ScriptError: could not find label 'nah'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 13, in script call
    call chapter1start
  File "game/scripts/chapter1.rpy", line 17, in script call
    call nah
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/scripts/script.rpy", line 13, in script call
    call chapter1start
  File "game/scripts/chapter1.rpy", line 17, in script call
    call nah
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'nah'.

macOS-14.3.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
dreamscapes 1.0
Fri Mar 15 01:44:24 2024
